version: '3.9'

services:
  frontend:
    build: ./frontend
    image: sewing-webapp-frontend:1.0.0 
    ports:
      - "80:80"
    environment: 
      - VITE_API_URL=${VITE_API_URL}
    restart: always

  backend:
    build: ./backend
    image: sewing-webapp-backend:1.0.0
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - database
    restart: always

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data: {}
